name: INSOFT
favicon: null
layout_spectrum: 0.14104
typography_spectrum: 0.14785
title: 'R&D in Ophtalmology'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#e31e24'
    - '#2b2a29'
    - '#ea585d'
    - '#f0898c'
  brandStrength: 0
  lightness: 0.9375
  saturation: 0.875
  rhythmicContrast: 1
purpose: []
