name: INSOFT
favicon: null
layout_spectrum: 1
typography_spectrum: 0.14189
title: "INSOFT's AI powered web-site"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#e31e24'
    - '#2b2a29'
    - '#ea585d'
    - '#f0898c'
  brandStrength: 0.5625
  lightness: 0.3125
  saturation: 0.5
  rhythmicContrast: 0.8116280871909112
purpose: []
