name: INSOFT
favicon: null
layout_spectrum: 0.41070058732293546
typography_spectrum: 0.7608930624555796
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e31e24'
    - '#2b2a29'
    - '#000000'
    - '#d50000'
    - '#800000'
  brandStrength: 0.7706646779552102
  lightness: 0.21634194790385664
  saturation: 0.8062075029592961
  rhythmicContrast: 0.8116280871909112
purpose: []
