name: INSOFT
favicon: null
layout_spectrum: 0.69278
typography_spectrum: 0.8079
title: "INSOFT's AI powered web-site"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e31e24'
    - '#2b2a29'
    - '#000000'
    - '#d50000'
    - '#800000'
  brandStrength: 0.5
  lightness: 0.3125
  saturation: 0.5
  rhythmicContrast: 0.8116280871909112
purpose: []
