typography_spectrum: 0.13972922088578343
color:
  brandColors:
    - '#ffffff'
    - '#e31e24'
    - '#2b2a29'
    - '#ea585d'
    - '#f0898c'
  brandStrength: 0
  lightness: 0.875
  saturation: 0.875
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.19807245093397796
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/f3edbadd-d45e-463b-bdbe-32c36fe22e8d.png
name: INSOFT SL
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: R&D in Ophthalmology
purpose: []
