layout_spectrum: 0.19807245093397796
typography_spectrum: 0.13972922088578343
color:
  brandColors:
    - '#ffffff'
    - '#e31e24'
    - '#2b2a29'
    - '#ea585d'
    - '#f0898c'
  brandStrength: 0
  lightness: 0.875
  saturation: 0.875
  rhythmicContrast: 1
name: INSOFT SL
favicon: null
title: R&D in Ophthalmology
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose: []
